### ISSUE TITLE
可以给个大模型吗

### ISSUE THREAD

**Issue by Y93936543** [zzy7517/novel2video#1]
筑梦动漫XL_v4.0 这个大模型下载不了了

**Comment by zzy7517** [comment]
可以去闲鱼找liblib代下，一块钱一个模型

**Comment by zzy7517** [comment]
我这里也有一些，不过可能不是最新的版本
我用夸克网盘分享了「sd模型」，点击链接即可保存。打开「夸克APP」，无需下载在线播放视频，畅享原画5倍速，支持电视投屏。
链接：https://pan.quark.cn/s/dba89d81425e
