### ISSUE TITLE
翻译失败

### ISSUE THREAD

**Issue by yytf007** [zzy7517/novel2video#3]
![image](https://github.com/user-attachments/assets/e7a83039-ec3b-4eff-a95e-0dbef8029ea6)
已实名认证
已填写api

后端问题：http://localhost:1198/ 打不开，The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

前端：提取角色是可以的。提取图像中的  翻译提示失败。

请问怎么解决？

**Comment by yytf007** [comment]
错误提升如下：
2024-12-09 13:51:44,607 - ERROR - translate prompts failed, err replace() argument 2 must be str, not dict [File: prompt.py, Line: 100]
2024-12-09 13:51:44,608 - INFO - 127.0.0.1 - - [09/Dec/2024 13:51:44] "GET /api/novel/prompts/en HTTP/1.1" 500 - [File: _internal.py, Line: 97]
2024-12-09 13:51:47,186 - ERROR - translate prompts failed, err replace() argument 2 must be str, not dict [File: prompt.py, Line: 100]
2024-12-09 13:51:47,187 - INFO - 127.0.0.1 - - [09/Dec/2024 13:51:47] "GET /api/novel/prompts/en HTTP/1.1" 500 - [File: _internal.py, Line: 97]

**Comment by zzy7517** [comment]
你这个文件保存的内容是什么 novel2video\temp\character\characters.txt

**Comment by yytf007** [comment]
{"\u59dc\u671b": "1lady, elegant purple dress, silver necklace, emerald eyes, curly long brown hair, high heels.", "\u4e5e\u4e10": "1lady, elegant purple dress, silver necklace, emerald eyes, curly long brown hair, high heels.", "\u5e84\u56fd\u6e05\u6cb3\u90e1\u67ab\u6797\u57ce\u59dc\u671b": {"error": "Failed to get random appearance"}, "\u5de6\u5149\u70c8": {"error": "Failed to get random appearance"}, "\u674e\u4e00": {"error": "Failed to get random appearance"}, "\u516c\u7f8a\u767d": "1lady, elegant purple dress, silver necklace, emerald eyes, curly long brown hair, high heels.", "\u58a8\u60ca\u7fbd": "1lady, elegant purple dress, silver necklace, emerald eyes, curly long brown hair, high heels.", "\u59dc\u671b\u7684\u6bcd\u4eb2": "1lady, elegant purple dress, silver necklace, emerald eyes, curly long brown hair, high heels.", "\u59dc\u671b\u7684\u7236\u4eb2": "1lady, elegant purple dress, silver necklace, emerald eyes, curly long brown hair, high heels.", "\u7fa4\u4e10": "1lady, elegant purple dress, silver necklace, emerald eyes, curly long brown hair, high heels."}

**Comment by yytf007** [comment]
现在有了新的问题：后端已开。只成果了一次后，前端怎么都没法保存了。

**Comment by yytf007** [comment]
老大，能帮我远程看看吗

**Comment by zzy7517** [comment]
可以

**Comment by yytf007** [comment]
麻烦加一下我的V :yytf007
