### ISSUE TITLE
翻译失败，与上一个提问者一样的情况 没有看到解决方法 请问大佬怎么解决

### ISSUE THREAD

**Issue by 767588507** [zzy7517/novel2video#4]
⨯ upstream image response failed for http://localhost:1198/images/placeholder.png 404
characters.txt
{"\u6c88\u5ff5": "\u6c88\u5ff5", "\u533b\u751f": "\u533b\u751f", "\u9646\u51cc\u5ddd": "\u9646\u51cc\u5ddd", "\u73b2\u73b2": "\u73b2\u73b2", "\u6c88\u5ff5\u7684\u7238\u5988": "\u6c88\u5ff5\u7684\u7238\u5988", "\u6c88\u5ff5\u7684\u7537\u670b\u53cb": "\u6c88\u5ff5\u7684\u7537\u670b\u53cb"}

2024-12-14 18:41:40,680 - ERROR - translate prompts failed, err Unexpected response status: 403, modelName google/gemma-2-9b-it [File: prompt.py, Line: 106]
2024-12-14 18:41:40,682 - INFO - 127.0.0.1 - - [14/Dec/2024 18:41:40] "GET /api/novel/prompts/en HTTP/1.1" 500 - [File: _internal.py, Line: 97]

**Comment by zzy7517** [comment]
@767588507 这个问题的原因是有一个模型在第三方平台已经不可用了，已经修复，你可以拉一下最新的代码，或者你本地直接把backend/llm/siliconflow.py这个文件的"google/gemma-2-9b-it"这一行删掉

**Comment by 767588507** [comment]
重新拉取了一下解决问题了，能翻译了，感谢大佬
就是现在生成音频和视频用不了报错这是部分报错信息
2024-12-16 09:28:29,455 - DEBUG - Using proactor: IocpProactor [File: proactor_events.py, Line: 631]
2024-12-16 09:28:29,841 - DEBUG - Using proactor: IocpProactor [File: proactor_events.py, Line: 631]
2024-12-16 09:28:30,041 - DEBUG - Using proactor: IocpProactor [File: proactor_events.py, Line: 631]
An unexpected error occurred for line 117, error: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=6cfa72bb3a8542a7afe7c232640e4934'
An unexpected error occurred for line 118, error: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=070c641a46b949a7b198a0c6e6abecbe'
An unexpected error occurred for line 93, error: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=304b6424870a4c169ea8404e4a66f9ec'
An unexpected error occurred for line 89, error: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=43041759a7d7415dadad7ea179d7a93c'

audio文件夹里会出现音频但是打不开提示文件损坏 没有显示文件大小

**Comment by zzy7517** [comment]
音频生成有问题的话 本地执行下这个 pip install --upgrade edge-tts

**Comment by 767588507** [comment]
执行后成功解决了，音频和视频都能成功生成，打开了，感谢大佬。
