### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by wzq530897296** [zzy7517/novel2video#5]
生成后的图片不显示，但是目录下有图片。
![1734519120973](https://github.com/user-attachments/assets/86d0308c-ba8c-4e3b-8051-88d206206bcb)
![1734519134927](https://github.com/user-attachments/assets/3c4b05a5-2260-429f-b3ca-8b9dfc4cac96)
![1734519197056](https://github.com/user-attachments/assets/61d04ecf-ad98-4ea1-9812-f24457fb4412)

**Comment by zzy7517** [comment]
后端用的哪个端口

**Comment by wzq530897296** [comment]
1198

**Comment by zzy7517** [comment]
发下后端命令行的输出吧

**Comment by zzy7517** [comment]
发下python服务的输出吧

**Comment by wzq530897296** [comment]
![1734915930411](https://github.com/user-attachments/assets/11dd3c12-61c0-4ea1-a3cc-3748ae40dd75)
![1734915869996](https://github.com/user-attachments/assets/3846682e-1a6b-40d3-8866-6a3991062b1e)

**Comment by wzq530897296** [comment]
![image](https://github.com/user-attachments/assets/ab8ac3e6-36de-46dd-8800-ed10b7288016)
da大佬 是不是这个的问题

**Comment by zzy7517** [comment]
你debug一下呢，只看日志的话看不太出来

**Comment by wzq530897296** [comment]
我在next.config.mjs 中添加了 unoptimized: true,  xi现在可以了
![1735557395085](https://github.com/user-attachments/assets/c056d161-64ea-4d02-9d69-dba278a7ff57)
